networks:
  tiny-sparrow-network:
    external: false
services:
  # VitePress 静态网站
  xiaolin-website:
    image: ghcr.nju.edu.cn/xiaolinstar/xiaolin-docs:main
    container_name: xiaolin-website
    volumes:
      - ./volumes/website/logs:/var/log/nginx
    networks:
      - tiny-sparrow-network
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      # 设置中国时区
      TZ: Asia/Shanghai
  
